apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-deployment
  labels:
    app: snakegame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snakegame
  template:
    metadata:
      labels:
        app: snakegame
    spec:
      containers:
      - name: snakegame
        image: cumakilinc/snakegame:v2.0
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: snakegame-service
spec:
  type: NodePort
  selector:
    app: snakegame
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30400